### ISSUE TITLE
Github Action Workflow

### ISSUE THREAD

**Issue by Abbhiishek** [Abbhiishek/Webners#5]
### Is your feature request related to a problem? Please describe
We want to greet every pull request and issue raised in the repository 
### Describe the solution you'd like
You can create a workflow for that 
```yaml
on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]
```
